---
- name: Deploying petclinic app with java
  become: true
  hosts: webservers
  vars:
    app_name: "spring-petclinic-3.2.1-SNAPSHOT.jar"
  tasks:
    - name: Install java
      ansible.builtin.apt:
        name: openjdk-17-jre
        state: present
    - name: Copy artifact to server
      ansible.builtin.copy:
        src: "{{ app_name }}"
        dest: /tmp/app.jar
        mode: "0755"
    - name: Launch the application
      ansible.builtin.command: java -jar /tmp/app.jar
      register: my_output 
      changed_when: "'Started PetClinicApplication' in my_output.stdout"
