---
- name: Deploying app with the help of Docker
  hosts: webservers
  become: true
  tasks:
    - name: Install Docker and pip
      ansible.builtin.apt:
        name: python3-pip, docker.io
        state: present
    - name: Start docker service
      ansible.builtin.service:
        name: docker
        state: started
    - name: Install docker python module
      pip:
        name: docker
    - name: Copy image archive to server
      ansible.builtin.copy:
        src: petclinic_image.tar
        dest: /tmp/petclinic_image.tar
        mode: "0755"
    - name: Build the image
      community.docker.docker_image:
        name: petclinic_image
        tag: 1.0
        source: load
        load_path: /tmp/petclinic_image.tar
    - name: Create the container
      community.docker.docker_container:
        name: petclinic_app
        image: petclinic_image:1.0
        state: started
        published_ports:
          - "8080:8080"
